name: Install Chrome

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  issues:
    types: [ opened, edited, reopened, labeled, unlabeled, closed ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17.0.8
          server-id: github
          settings-path: ${{ github.workspace }}
      - name: Install Google Chrome
        uses: browser-actions/setup-chrome@latest
      - run: chrome --version

      - name: Build with Maven
        run: mvn -B package --file pom.xml test